spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
